### ISSUE TITLE
Exploratory Data Analysis

### ISSUE THREAD

**Issue by yutingmeivu** [rileymccarty/Average_Joes_Ancient_Artifacts#6]
- **Identify the problem you want to analyze**
---

- **Find target variables and filter disturbing variables**
---

- **Before plotting**

     To clarify the core information conveyed by the chart, consider the following aspects:
- [ ] 1. What variable are we trying to plot?
- [ ] 2. What do the x-axis and axis represent?
- [ ] 3. Does the size of the data points have any meaning?
- [ ] 4. Does the color mean anything?
- [ ] 5. Are we trying to identify trends over time, or relationships between variables?
---

- **Choose the right chart type**
---

- **Direct attention to key information**
---

- **Get Conclusion**
- [ ] Summarize key information and make it clearer and more straightforward, without confusing or overloading the reader's brain with a lot of information

**Comment by ZhuoyiZhan** [comment]
We can add comparison of the lithic microdebitage and archeology soil on the variable "Transparency". Because when curving tool, the microdebitages are in form of chips which may be transparent or opaque.

**Comment by mayingxiang** [comment]
Completed the EDA process, closing issue now.
